### ISSUE TITLE
Observation tensor size error

### ISSUE THREAD

**Issue by mfe7** [maximecb/gym-minigrid#16]
I'm unable to train the model with the provided pytorch `main.py` script with `--num-processes` > 1.

When I run this command:
```
$ python3 /home/mfe/code/gyms/gym-minigrid/pytorch_rl/main.py --env-name MiniGrid-Empty-8x8-v0 --no-vis --num-processes 5 --algo a2c
```

The error I get is:
```
obs.shape: (5, 1875)
shape_dim0: 1
current_obs.shape: torch.Size([5, 1, 1875])
current_obs.shape: torch.Size([5, 1, 1875])
Traceback (most recent call last):
  File "/home/mfe/code/gyms/gym-minigrid/pytorch_rl/main.py", line 271, in <module>
    main()
  File "/home/mfe/code/gyms/gym-minigrid/pytorch_rl/main.py", line 98, in main
    update_current_obs(obs)
  File "/home/mfe/code/gyms/gym-minigrid/pytorch_rl/main.py", line 95, in update_current_obs
    current_obs[:, -shape_dim0:] = obs
RuntimeError: The expanded size of the tensor (1) must match the existing size (5) at non-singleton dimension 1
```

I believe this is related to the code on line 86 of `main.py`:

```
def update_current_obs(obs):
        print("obs.shape:", obs.shape)
        shape_dim0 = envs.observation_space.shape[0]
        print("shape_dim0:", shape_dim0)
        obs = torch.from_numpy(obs).float()
        print("current_obs.shape:", current_obs.shape)
        if args.num_stack > 1:
            current_obs[:, :-shape_dim0] = current_obs[:, shape_dim0:]
        print("current_obs.shape:", current_obs.shape)
        current_obs[:, -shape_dim0:] = obs
```

**Comment by maximecb** [comment]
Hi there!

The RL code in this repository is unfortunately not very good. I'm going to remove it and update the readme. I recommend instead using this implementation: https://github.com/lcswillems/pytorch-a2c-ppo

It was actually written by someone I know, and tested on this environment.

Sample training command:
```
python3 -m scripts.train --env MiniGrid-Empty-8x8-v0 --algo ppo
```

**Comment by mfe7** [comment]
Thanks! I'll try out that repo
