### ISSUE TITLE
size mismatch when using FullyObsWrapper

### ISSUE THREAD

**Issue by Driesssens** [maximecb/gym-minigrid#28]
When using the FullyObsWrapper (and using the recommended A2C algorithm from https://github.com/lcswillems/pytorch-a2c-ppo), no issues arise when training on a 8x8 grid. However, on a 16x16 grid the following happens:

```
Traceback (most recent call last):
  File "C:\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\pytorch-a2c-ppo\scripts\train.py", line 157, in <module>
    logs = algo.update_parameters()
  File "c:\pytorch-a2c-ppo\torch_rl\torch_rl\algos\ppo.py", line 32, in update_parameters
    exps, logs = self.collect_experiences()
  File "c:\pytorch-a2c-ppo\torch_rl\torch_rl\algos\base.py", line 131, in collect_experiences
    dist, value, memory = self.acmodel(preprocessed_obs, self.memory * self.mask.unsqueeze(1))
  File "C:\Python36\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\pytorch-a2c-ppo\model.py", line 94, in forward
    x = self.actor(embedding)
  File "C:\Python36\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Python36\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "C:\Python36\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Python36\lib\site-packages\torch\nn\modules\linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Python36\lib\site-packages\torch\nn\functional.py", line 1024, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [16 x 1600], m2: [64 x 64] at c:\new-builder_2\win-wheel\pytorch\aten\src\th\generic/THTensorMath.cpp:2070
```

Any ideas as what could be the cause of this?

**Comment by maximecb** [comment]
Yes, the problem is that with a fully observable grid, the size of your observation is the size of the grid. I unfortunately don't know of a way to automatically adjust the convolutional layer sizes in PyTorch, so you have to manually adjust these so that the size of the tensors being passed through operations match:

Convolutional layers:
https://github.com/lcswillems/pytorch-a2c-ppo/blob/master/model.py#L26

You could also pad the size of the embedding after the convolution, or make it go through a fully-connected layer to get an embedding of the size you want:
https://github.com/lcswillems/pytorch-a2c-ppo/blob/master/model.py#L80

**Comment by lcswillems** [comment]
This is normal. The default model is made to take as input a 7x7x3 image. It applies convolutions hence assumes the output has size 64 (https://github.com/lcswillems/pytorch-a2c-ppo/blob/9e87fdad55c1139526a8228dfe15d0b667fbedae/model.py#L25). So you should modify this number.

I am modifying my code to do it automatically

**Comment by maximecb** [comment]
@lcswillems Awesome if you can do it automatically! 👍

**Comment by lcswillems** [comment]
This is done. Now, the model adapts to the observation space (https://github.com/lcswillems/pytorch-a2c-ppo/blob/e37dd17f9115c08b4234cc85b38f7429c9623560/model.py#L36). However, keep in mind that the model created automatically for the fully-observable space is not necessarily the best.

**Comment by Driesssens** [comment]
Of course. Browsed through that code to see if the input size was hardcoded, but didn't realize a fixed CNN output size implies a fixed input size too. Thanks for the quick replies!
